const { execSync } = require('child_process');
const post = async (port, path, body) => { const t = Date.now(); const r = await fetch('http://127.0.0.1:' + port + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body || {}) }); const j = await r.json(); j.ms = Date.now() - t; return j; };
const sql = q => execSync('su postgres -c "psql -d rcl -tAc \\"' + q + '\\""').toString().trim();
const dump = async () => (await fetch('http://127.0.0.1:3997/dump')).json();
const ok = (name, cond, extra) => console.log((cond ? 'PASS ' : 'FAIL ') + name + (extra ? '  ' + extra : ''));
(async () => {
  sql("delete from web.props where key in ('BK_STATE','SB_INFO')");
  const token = (await post(3000, '/api/rpc', { fn: 'login', args: ['sujit@rcl.test', 'Nashik#Road848!'] })).result.token;
  const api = (port, fn, ...a) => post(port, '/api/rpc', { fn: 'api', args: [token, fn, a] });
  let r = await api(3000, 'backupNow'); ok('a tab still protected by the old backup → a clear message, nothing half-written', /protected/.test(r.error || '') && /Master/.test(r.error || ''), String(r.error).slice(0, 230));
  let d0 = await dump(); ok('…and the Sheet was not touched', d0.tabs.find(x => x.title === 'Log Book').rows === 1);
  r = await api(3000, 'sync'); ok('…and the app shows the backup as failed', r.result.backup && r.result.backup.ok === false, String(r.result.backup && r.result.backup.error).slice(0, 80));
  await fetch('http://127.0.0.1:3997/unprotect'); sql("delete from web.props where key in ('BK_STATE')");
  r = await post(3000, '/api/backup', { token }); ok('first backup (the page asking)', r.ok === true && !r.skipped, JSON.stringify(r));
  let d = await dump(); const tab = t => d.tabs.find(x => x.title === t) || {};
  const nLog = Number(sql('select count(*) from log_book')), nDi = Number(sql('select count(*) from diesel_issue')), nAct = Number(sql('select count(*) from activity_log'));
  ok('tabs made', d.tabs.length >= 17, d.tabs.map(x => x.title).join(', '));
  ok('Log Book tab = database rows + heading', tab('Log Book').rows === nLog + 1, tab('Log Book').rows + ' rows, grid ' + JSON.stringify(tab('Log Book').grid));
  ok('headings are the app\'s own names', JSON.stringify(tab('Log Book').head).indexOf('Machinery Number') > -1, JSON.stringify(tab('Log Book').head));
  ok('Diesel Issue tab', tab('Diesel Issue').rows === nDi + 1);
  const users = d.tabs.find(x => /user/i.test(x.title)); ok('passwords are not copied', JSON.stringify(users.second).indexOf('(hidden)') > -1 && JSON.stringify(users.second).indexOf('sha256') === -1, JSON.stringify(users.head) + ' ' + JSON.stringify(users.second));
  ok('Backup Status page', tab('Backup Status').rows > 5, JSON.stringify(tab('Backup Status').second));
  r = await post(3001, '/api/backup', { token }); ok('asked again at once → left alone', r.skipped === true, JSON.stringify(r));
  r = await api(3000, 'backupNow'); ok('"Backup" button when nothing changed… (the sign-in itself wrote the Activity Log)', !r.error, JSON.stringify(r.result).slice(0, 160));
  r = await api(3000, 'backupNow'); ok('…and again', !r.error && (r.result.upToDate || r.result.lines), JSON.stringify(r.result).slice(0, 200));
  r = await api(3000, 'saveDieselIssue', { date: '2026-09-30', shift: 'Night', source: 'Dispenser', no: 'MH-15-AB-0002', qty: 7, kmReading: 99500, driver: 'BK' }); const id = r.result.id;
  r = await api(3001, 'backupNow'); ok('after a save: only the changed tables are copied', !r.error && r.result.lines && r.result.lines.some(x => x[0] === 'Diesel Issue') && !r.result.lines.some(x => x[0] === 'Master') , JSON.stringify(r.result.lines));
  d = await dump(); ok('Diesel Issue tab has the new row', tab('Diesel Issue').rows === nDi + 2);
  await api(3000, 'deleteDieselIssue', id); r = await api(3000, 'backupNow'); d = await dump();
  ok('after a delete the tab is short again', tab('Diesel Issue').rows === nDi + 1 && tab('Diesel Issue').grid.rowCount === nDi + 1, 'rows ' + tab('Diesel Issue').rows + ', grid ' + tab('Diesel Issue').grid.rowCount);
  r = await api(3000, 'sync'); ok('the app shows the backup time and the link', r.result.backup && r.result.backup.ok === true && /docs.google.com/.test(r.result.backup.url), JSON.stringify(r.result.backup));
  r = await fetch('http://127.0.0.1:3000/api/backup?full=1', { headers: { Authorization: 'Bearer local-cron-secret' } }); const j = await r.json(); const noProof = await (await fetch('http://127.0.0.1:3000/api/backup?full=1')).json(); ok('nightly job without its proof is refused', noProof.denied === true, JSON.stringify(noProof)); d = await dump(); ok('nightly full backup (GET ?full=1)', j.ok === true, JSON.stringify(j) + ' · Google calls so far ' + d.calls);
  const cron = port => fetch('http://127.0.0.1:' + port + '/api/backup?full=1', { headers: { Authorization: 'Bearer local-cron-secret' } }).then(x => x.json()); const many = await Promise.all([cron(3000), cron(3001)]); ok('two at the same moment: one runs, the other waits out', many.filter(x => x.busy).length >= 1 || many.every(x => x.ok), JSON.stringify(many));
  ok('no lock left', sql('select count(*) from web.locks') === '0');
})().catch(e => console.log('CRASH', e));
