// Start reading: proposed from the last Close, may be typed higher (ran elsewhere), never lower – through the page and the database
const chromium = require('@sparticuz/chromium').default || require('@sparticuz/chromium'); const puppeteer = require('puppeteer-core');
const fs = require('fs'); const { execSync } = require('child_process');
const wait = ms => new Promise(r => setTimeout(r, ms)); const sql = q => execSync('su postgres -c "psql -d rcl -tA"', { input: q }).toString().trim();
const rpc = async (fn, ...args) => (await fetch('http://127.0.0.1:3001/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fn, args }) })).json();
const out = []; let pass = 0, fail = 0; const ok = (n, c, x) => { c ? pass++ : fail++; out.push((c ? 'PASS ' : 'FAIL ') + n + (x !== undefined ? '  → ' + String(typeof x === 'string' ? x : JSON.stringify(x)).slice(0, 320) : '')); };
(async () => {
  const tk = (await rpc('login', 'sujit@rcl.test', 'Nashik#Road848!')).result.token;
  await rpc('api', tk, 'saveMaster', [{ no: 'GAPX-1', name: 'Tipper', type: 'Tipper', unit: 'KM', worksOn: ['KM'], kmStd: 4, owner: 'Vendor 5', ownership: 'Rental', supply: 'Debit Basis', status: 'Active', activeFrom: '2026-09-01' }, 'add']);
  sql("delete from log_book where machinery = 'GAPX-1'");
  const b = await puppeteer.launch({ executablePath: await chromium.executablePath(), args: [...chromium.args, '--no-sandbox'], headless: 'shell', protocolTimeout: 120000 });
  const p = await b.newPage(); await p.setViewport({ width: 1536, height: 760 });
  const errs = []; p.on('pageerror', e => errs.push(String(e.message).slice(0, 200)));
  await p.goto('http://127.0.0.1:3000/', { waitUntil: 'load' }); await wait(800);
  const f = p.frames().find(x => x !== p.mainFrame());
  await f.type('#lg_email', 'sujit@rcl.test'); await f.type('#lg_pass', 'Nashik#Road848!'); await f.click('#lg_btn'); await wait(5000);
  const okDlg = () => f.evaluate(() => { const c = document.getElementById('cf_back'); if (c && !c.hidden) { document.getElementById('cf_ok').click(); return true; } return false; });
  await f.evaluate(() => { try { closeConfirm(false); } catch (e) {} showTab('log'); }); await wait(3000); await f.evaluate(() => { try { closeConfirm(false); } catch (e) {} });
  const openRow = async date => { await f.evaluate(async d => { setLgMode('date'); const dt = document.getElementById('lg_top_date'); dt.value = d; dt.dispatchEvent(new Event('change', { bubbles: true })); await new Promise(r => setTimeout(r, 600));
      const tr = document.querySelector('#lg_in .lrow'); const x = tr.querySelector('[data-f=no]'); x.value = 'GAPX-1'; x.dispatchEvent(new Event('change', { bubbles: true })); }, date);
    for (let i = 0; i < 30; i++) { await wait(500); if (await f.evaluate(d => { const tr = document.querySelector('#lg_in .lrow'); return !!(tr && tr._p && tr._p.machine.id === 'GAPX-1' && tr._key && tr._key.indexOf(d) > -1); }, date)) break; } await f.evaluate(() => lgCalcAll()); };
  const setF = (k, v) => f.evaluate((k2, v2) => { const el = document.querySelector('#lg_in .lrow [data-f=' + k2 + ']'); el.value = v2; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); lgCalcAll(); }, k, v);
  const state = () => f.evaluate(() => { lgCalcAll(); const tr = document.querySelector('#lg_in .lrow'), o = tr.querySelector('[data-f=openingKm]'), bx = document.getElementById('fixbox'); return { start: o.value, locked: o.readOnly, red: tr.classList.contains('err'), note: (tr.querySelector('.c-m .lnote') || {}).textContent || '', gap: tr.querySelector('.gaphint').hidden ? '' : tr.querySelector('.gaphint').textContent, total: tr.querySelector('[data-o=wkm]').textContent, card: bx && !bx.hidden ? bx.querySelector('.fx-msg').textContent.slice(0, 120) : '' }; });
  const save = async () => { await f.evaluate(() => document.getElementById('l_save').click()); for (let i = 0; i < 14; i++) { await wait(500); await okDlg(); } return f.evaluate(() => { const bx = document.getElementById('fixbox'); return bx && !bx.hidden ? bx.textContent.replace(/\s+/g, ' ').slice(0, 800) : ''; }); };
  const row = d => sql("select opening_km || '|' || closing_km || '|' || working_km from log_book where id = 'GAPX-1|" + d + "|Full Day'");
  await openRow('2026-09-30'); await setF('openingKm', '1000'); await setF('closingKm', '1100'); await save();
  ok('day 1 saved: 1000 → 1100 = 100 km', row('2026-09-30') === '1000|1100|100', row('2026-09-30'));
  await openRow('2026-10-01'); let st = await state();
  ok('day 2: Start is proposed (1100) and the box is open for typing', st.start === '1100' && !st.locked && !st.red, st);
  await setF('openingKm', '1090'); st = await state();
  ok('a LOWER Start (1090) is pointed out at once and the row is red', st.red && /Start KM 1090 is less than the last Close KM 1100/.test(st.note) && /Start KM 1090 is less than the last Close KM 1100/.test(st.card), st);
  await setF('closingKm', '1200'); let r = await save();
  ok('…and Save refuses it, with what to do in Marathi', row('2026-10-01') === '' && /काय करायचे/.test(r) && /less than the last Close/.test(r), r.slice(0, 200));
  await f.evaluate(() => { const bx = document.getElementById('fixbox'); if (bx) bx.hidden = true; });
  await setF('openingKm', '1150'); st = await state();
  ok('a HIGHER Start (1150): accepted, the row says "50 km ran elsewhere – not counted", work = 50 km', !st.red && /50 km ran elsewhere – not counted/.test(st.gap) && /^50/.test(st.total), st);
  await p.screenshot({ path: 'shots/start_gap.png' }); await save();
  ok('saved: Start 1150, Close 1200, 50 km (the 50 km in between are in no entry)', row('2026-10-01') === '1150|1200|50', row('2026-10-01'));
  await openRow('2026-10-02'); st = await state(); await setF('closingKm', '1260'); await save();
  ok('day 3: nothing typed in Start → it is the last Close (1200); saved 1200 → 1260', st.start === '1200' && row('2026-10-02') === '1200|1260|60', st.start + ' / ' + row('2026-10-02'));
  ok('no script error', errs.length === 0, errs.join(' | '));
  out.push(pass + ' passed, ' + fail + ' failed'); fs.writeFileSync('/tmp/start.out', out.join('\n')); await b.close();
})().catch(e => { fs.writeFileSync('/tmp/start.out', out.join('\n') + '\nCRASH ' + String(e.stack || e).slice(0, 500)); process.exit(1); });
